### ISSUE TITLE
Geode crashes when dying (Android)

### ISSUE THREAD

**Issue by denyallow-dev** [kittenchilly/Randomize-Icon-on-Death#1]
When you enter to the level, you start with randomized icons. If you would try to due, game freezes and crashes. Every time. Probably incompatibility with some mods. Personally I have many mods installed (~90).

**Comment by kittenchilly** [comment]
Yes, I imagine that's some kind of mod incompatibility. Do you have any other mod that does something when dying?

**Comment by denyallow24** [comment]
> Yes, I imagine that's some kind of mod incompatibility. Do you have any other mod that does something when dying?

No, but everytime I die my mod menu shows hitboxes. I turned it off, but game still crashes.

**Comment by kittenchilly** [comment]
Actually do you think you can disable every mod except this one and see if it still crashes?

**Comment by denyallow24** [comment]
> Actually do you think you can disable every mod except this one and see if it still crashes?

Yes, I did it. It still crashes which is means that's exactly this mod problem.

**Comment by kittenchilly** [comment]
Can you check if it still crashes with v1.0.4?

**Comment by denyallow24** [comment]
> Can you check if it still crashes with v1.0.4?

I have updated geode to v3.1.0, and I don't see this mod in download tab. Maybe share the file?

**Comment by kittenchilly** [comment]
> > Can you check if it still crashes with v1.0.4?
> 
> I have updated geode to v3.1.0, and I don't see this mod in download tab. Maybe share the file?

Ok, it just got published so try looking for it on the download tab now

**Comment by denyallow24** [comment]
> Ok, it just got published so try looking for it on the download tab now

Not it works just fine and not crashes. The only thing I don't like is that your icons change completely. You'll need to back your icons by yourself.

**Comment by kittenchilly** [comment]
That's something unrelated to the issue but you can make another issue for that if you want, so I'm closing it now
