### ISSUE TITLE
Spider and Robot not switching on death

### ISSUE THREAD

**Issue by NagusPacka** [kittenchilly/Randomize-Icon-on-Death#3]
Spider and Robot only change when you start a new level. I tried keeping only the mod activated (to assert if another mod could cause it), but still happens just with those gamemodes

**Comment by kittenchilly** [comment]
Seems to be fixed with v1.0.4 now, in my testing at least. Make another issue if this is still broken in some way lol

**Comment by NagusPacka** [comment]
@kittenchilly Hi there again, I haven't played in a while and just update the mod but for some reason the icons don't randomize, I tried to uninstall geode for a "clean" test just to assert if another mod could cause the issue but still don't randomize. I don't know if I miss something else (I had both better randomizer and API) or if there is a known issue I'm not aware (and I don't think it is a bug that's because I didn't want to make another issue)

**Comment by kittenchilly** [comment]
@NagusPacka 
I updated the mod, please check if its fixed now as it works for me and idk if its another issue

**Comment by NagusPacka** [comment]
Yay, it works now, thank you so much
