### ISSUE TITLE
Missing texture death effects

### ISSUE THREAD

**Issue by p6w1** [kittenchilly/Randomize-Icon-on-Death#4]
Just like the title says, whenever I have this mod enabled, the death effects are missing texture (the purple and black checkerboard seen in the screenshot)

It could be conflicting mods but I'm not too sure, I don't have a texture pack on and the missing textures only appear after I enable this mod

![20240625084703_1](https://github.com/kittenchilly/Randomize-Icon-on-Death/assets/173803537/017b3ff1-73aa-4b83-b9d4-9c2b979f87c0)

**Comment by kittenchilly** [comment]
Are you on Windows? Can you try enabling just this mod and nothing else and see if it still happens?

**Comment by p6w1** [comment]
I'm using Windows 10, yes

Only having this mod enabled now straight up crashes my game if I die in game

[2024-06-25_15-36-26.log](https://github.com/user-attachments/files/15977397/2024-06-25_15-36-26.log)

**Comment by kittenchilly** [comment]
Ok, can you try to verify integrity of files through steam and see if it stops the crash? It looks like its because "playerExplosion_11_001.png" doesn't exist in your files for some reason, possibly due to an error some texture pack made that deleted it somehow.

**Comment by p6w1** [comment]
I ran it as you said, and it's still crashing

[2024-06-25_15-54-04.log](https://github.com/user-attachments/files/15977683/2024-06-25_15-54-04.log)

**Comment by kittenchilly** [comment]
I believe this should be fixed now with the latest version, could you check?

**Comment by p6w1** [comment]
Yes, it no longer crashes, turns out a mod produces the missing texture when it can't find a texture, probably to prevent crashes, so nothing to worry about now, thanks for the fix
