### ISSUE TITLE
Geometry Dash crashes when using this mod. (Windows 11)

### ISSUE THREAD

**Issue by Skelolton** [kittenchilly/Randomize-Icon-on-Death#5]
The mod works for a little bit. But once i die after about 5 deaths it crashes my whole game.

I also disabled every other mod i have except for this one and it still crashes. If you can try to fix it that would be great.

**Comment by kittenchilly** [comment]
Can you send crash logs? I'm also on Windows 11 and it doesn't crash at all for me

**Comment by Skelolton** [comment]
[2024-06-25_16-13-01.log](https://github.com/user-attachments/files/15976757/2024-06-25_16-13-01.log)

I only had the randomizer mod enabled with this crashlog.

**Comment by kittenchilly** [comment]
I noticed you had openhack? Did you have it's unlock all icons thing enabled?

**Comment by kittenchilly** [comment]
NVM, I don't think thats the issue

**Comment by Skelolton** [comment]
nah i didn't have it enabled

**Comment by kittenchilly** [comment]
Ok, can you try to verify integrity of files through steam and see if it stops the crash? It looks like its because "playerExplosion_11_001.png" doesn't exist in your files for some reason, possibly due to an error some texture pack made that deleted it somehow.

**Comment by Skelolton** [comment]
I did that and it still crashes.

**Comment by Skelolton** [comment]
Nevermind. After the update it doesn't crash anymore. Thank you! I will now close this issue.
